-- ============================================================================
--  DH 스마트파워 변압기 통합 모니터링 시스템
--  PostgreSQL 스키마  (Supabase 제거 후 자체 구축용)
--
--  적용:  psql "$DATABASE_URL" -f db/schema.sql
--  이 파일은 반복 실행해도 안전합니다 (IF NOT EXISTS / OR REPLACE).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. 사용자 및 인증
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL,
  full_name     text,
  -- 형식: scrypt$N$r$p$<salt base64url>$<hash base64url>
  password_hash text NOT NULL,
  tier          text NOT NULL DEFAULT 'viewer' CHECK (tier IN ('viewer', 'admin')),
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz
);

-- 이메일은 대소문자 구분 없이 유일해야 합니다.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key ON users (lower(email));

-- 서버측 세션. 쿠키에는 세션 id의 HMAC 서명본만 담고 실제 권한은 여기서 조회합니다.
CREATE TABLE IF NOT EXISTS sessions (
  id         text PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  ip         text,
  user_agent text
);

CREATE INDEX IF NOT EXISTS sessions_user_idx    ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS login_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES users(id) ON DELETE SET NULL,
  email      text,
  success    boolean NOT NULL DEFAULT true,
  ip         text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS login_events_created_idx ON login_events (created_at DESC);

-- ----------------------------------------------------------------------------
-- 2. 설비 및 브리지
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bridges (
  bridge_id    text PRIMARY KEY,
  name         text NOT NULL,
  online       boolean NOT NULL DEFAULT false,
  fw_version   text,
  rssi         integer,
  last_seen_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
  device_id  text PRIMARY KEY,
  name       text NOT NULL,
  building   text NOT NULL DEFAULT '',
  capacity   text NOT NULL DEFAULT '',
  bridge_id  text REFERENCES bridges(bridge_id) ON DELETE SET NULL,
  slave_addr integer,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS devices_sort_idx ON devices (sort_order, device_id);

-- ----------------------------------------------------------------------------
-- 3. 계측 데이터
-- ----------------------------------------------------------------------------

-- 설비별 최신값. 수집 서버(MQTT)가 이 테이블에 upsert 합니다.
CREATE TABLE IF NOT EXISTS device_readings (
  device_id   text PRIMARY KEY REFERENCES devices(device_id) ON DELETE CASCADE,
  h2          double precision,
  ch4         double precision,
  temperature double precision,
  oil_level   text,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- 원본 계측 이력. 추세 그래프와 사후 분석에 사용합니다.
-- (device_id, measured_at) 유일 제약이 MQTT QoS 1의 중복 수신을 걸러냅니다.
CREATE TABLE IF NOT EXISTS telemetry (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id   text NOT NULL,
  h2          double precision,
  ch4         double precision,
  temperature double precision,
  oil_level   text,
  measured_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (device_id, measured_at)
);

CREATE INDEX IF NOT EXISTS telemetry_device_time_idx ON telemetry (device_id, measured_at DESC);

-- ----------------------------------------------------------------------------
-- 4. 설정 및 알람
-- ----------------------------------------------------------------------------

-- 단일 행(id=1)만 존재합니다. 브라우저 localStorage를 대체하여
-- 모든 관리자가 동일한 판정 기준을 보도록 합니다.
CREATE TABLE IF NOT EXISTS app_config (
  id         integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  thresholds jsonb NOT NULL,
  version    integer NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS alarm_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id  text,
  unit       text NOT NULL,
  item       text NOT NULL,
  level      text NOT NULL CHECK (level IN ('caution', 'warning', 'danger')),
  detail     text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS alarm_events_created_idx ON alarm_events (created_at DESC);
CREATE INDEX IF NOT EXISTS alarm_events_device_idx  ON alarm_events (device_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- 5. 실시간 통지 (Supabase Realtime 대체)
--    수집 서버가 device_readings 를 갱신하면 NOTIFY 가 발생하고,
--    Next.js 의 SSE 스트림 라우트가 이를 받아 브라우저로 밀어줍니다.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION notify_device_reading() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('device_reading', json_build_object(
    'device_id',   NEW.device_id,
    'h2',          NEW.h2,
    'ch4',         NEW.ch4,
    'temperature', NEW.temperature,
    'oil_level',   NEW.oil_level,
    'updated_at',  NEW.updated_at
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS device_readings_notify ON device_readings;
CREATE TRIGGER device_readings_notify
  AFTER INSERT OR UPDATE ON device_readings
  FOR EACH ROW EXECUTE FUNCTION notify_device_reading();

CREATE OR REPLACE FUNCTION notify_alarm_event() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('alarm_event', json_build_object(
    'id',         NEW.id,
    'device_id',  NEW.device_id,
    'unit',       NEW.unit,
    'item',       NEW.item,
    'level',      NEW.level,
    'detail',     NEW.detail,
    'created_at', NEW.created_at
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS alarm_events_notify ON alarm_events;
CREATE TRIGGER alarm_events_notify
  AFTER INSERT ON alarm_events
  FOR EACH ROW EXECUTE FUNCTION notify_alarm_event();

-- ----------------------------------------------------------------------------
-- 6. 기본 설정값
-- ----------------------------------------------------------------------------

INSERT INTO app_config (id, thresholds)
VALUES (1, '{
  "h2":          { "caution": 20, "warning": 50, "danger": 100 },
  "ch4":         { "caution": 15, "warning": 30, "danger": 60  },
  "temperature": { "caution": 55, "warning": 65, "danger": 75  },
  "hysteresisMarginPct": 0.1,
  "compositeEnabled": true,
  "compositeMinSensors": 2,
  "offlineMinutes": 15
}'::jsonb)
ON CONFLICT (id) DO NOTHING;
