-- ============================================================================
--  DH 스마트파워 변압기 통합 모니터링 시스템
--  PostgreSQL 스키마  (Supabase 제거 후 자체 구축용)
--
--  적용:  psql "$DATABASE_URL" -f db/schema.sql
--  이 파일은 반복 실행해도 안전합니다 (IF NOT EXISTS / OR REPLACE).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. 사용자 및 인증
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL,
  full_name     text,
  -- 형식: scrypt$N$r$p$<salt base64url>$<hash base64url>
  password_hash text NOT NULL,
  tier          text NOT NULL DEFAULT 'viewer' CHECK (tier IN ('viewer', 'admin')),
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz
);

-- 이메일은 대소문자 구분 없이 유일해야 합니다.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key ON users (lower(email));

-- 서버측 세션. 쿠키에는 세션 id의 HMAC 서명본만 담고 실제 권한은 여기서 조회합니다.
CREATE TABLE IF NOT EXISTS sessions (
  id         text PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  ip         text,
  user_agent text
);

CREATE INDEX IF NOT EXISTS sessions_user_idx    ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS login_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES users(id) ON DELETE SET NULL,
  email      text,
  success    boolean NOT NULL DEFAULT true,
  ip         text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS login_events_created_idx ON login_events (created_at DESC);

-- ----------------------------------------------------------------------------
-- 2. 설비 및 브리지
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bridges (
  bridge_id    text PRIMARY KEY,
  name         text NOT NULL,
  online       boolean NOT NULL DEFAULT false,
  fw_version   text,
  rssi         integer,
  last_seen_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
  device_id  text PRIMARY KEY,
  name       text NOT NULL,
  building   text NOT NULL DEFAULT '',
  capacity   text NOT NULL DEFAULT '',
  bridge_id  text REFERENCES bridges(bridge_id) ON DELETE SET NULL,
  slave_addr integer,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS devices_sort_idx ON devices (sort_order, device_id);

-- ----------------------------------------------------------------------------
-- 3. 계측 데이터
-- ----------------------------------------------------------------------------

-- 설비별 최신값. 수집 서버(MQTT)가 이 테이블에 upsert 합니다.
CREATE TABLE IF NOT EXISTS device_readings (
  device_id   text PRIMARY KEY REFERENCES devices(device_id) ON DELETE CASCADE,
  h2          double precision,
  ch4         double precision,
  temperature double precision,
  oil_level   text,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- 원본 계측 이력. 추세 그래프와 사후 분석에 사용합니다.
-- (device_id, measured_at) 유일 제약이 MQTT QoS 1의 중복 수신을 걸러냅니다.
CREATE TABLE IF NOT EXISTS telemetry (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id   text NOT NULL,
  h2          double precision,
  ch4         double precision,
  temperature double precision,
  oil_level   text,
  measured_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (device_id, measured_at)
);

CREATE INDEX IF NOT EXISTS telemetry_device_time_idx ON telemetry (device_id, measured_at DESC);

-- ----------------------------------------------------------------------------
-- 4. 설정 및 알람
-- ----------------------------------------------------------------------------

-- 단일 행(id=1)만 존재합니다. 브라우저 localStorage를 대체하여
-- 모든 관리자가 동일한 판정 기준을 보도록 합니다.
CREATE TABLE IF NOT EXISTS app_config (
  id         integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  thresholds jsonb NOT NULL,
  version    integer NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS alarm_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id  text,
  unit       text NOT NULL,
  item       text NOT NULL,
  level      text NOT NULL CHECK (level IN ('caution', 'warning', 'danger')),
  detail     text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS alarm_events_created_idx ON alarm_events (created_at DESC);
CREATE INDEX IF NOT EXISTS alarm_events_device_idx  ON alarm_events (device_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- 5. 실시간 통지 (Supabase Realtime 대체)
--    수집 서버가 device_readings 를 갱신하면 NOTIFY 가 발생하고,
--    Next.js 의 SSE 스트림 라우트가 이를 받아 브라우저로 밀어줍니다.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION notify_device_reading() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('device_reading', json_build_object(
    'device_id',   NEW.device_id,
    'h2',          NEW.h2,
    'ch4',         NEW.ch4,
    'temperature', NEW.temperature,
    'oil_level',   NEW.oil_level,
    'updated_at',  NEW.updated_at
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS device_readings_notify ON device_readings;
CREATE TRIGGER device_readings_notify
  AFTER INSERT OR UPDATE ON device_readings
  FOR EACH ROW EXECUTE FUNCTION notify_device_reading();

CREATE OR REPLACE FUNCTION notify_alarm_event() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('alarm_event', json_build_object(
    'id',         NEW.id,
    'device_id',  NEW.device_id,
    'unit',       NEW.unit,
    'item',       NEW.item,
    'level',      NEW.level,
    'detail',     NEW.detail,
    'created_at', NEW.created_at
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS alarm_events_notify ON alarm_events;
CREATE TRIGGER alarm_events_notify
  AFTER INSERT ON alarm_events
  FOR EACH ROW EXECUTE FUNCTION notify_alarm_event();

-- ----------------------------------------------------------------------------
-- 6. 기본 설정값
-- ----------------------------------------------------------------------------

INSERT INTO app_config (id, thresholds)
VALUES (1, '{
  "h2":          { "caution": 20, "warning": 50, "danger": 100 },
  "ch4":         { "caution": 15, "warning": 30, "danger": 60  },
  "temperature": { "caution": 55, "warning": 65, "danger": 75  },
  "hysteresisMarginPct": 0.1,
  "compositeEnabled": true,
  "compositeMinSensors": 2,
  "offlineMinutes": 15
}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 7. 알람 발송 (메신저 · 문자 · 메일)
--    알람이 생기면 등록된 수신자에게 각자 지정한 경로로 보냅니다.
--    반복 실행해도 안전합니다.
-- ----------------------------------------------------------------------------

-- 채널별 연동 정보. config 에는 API 키 같은 비밀값이 들어가므로
-- 화면으로는 절대 그대로 내려보내지 않고 가린 값만 보여줍니다.
CREATE TABLE IF NOT EXISTS notify_channels (
  channel    text PRIMARY KEY
             CHECK (channel IN ('telegram', 'sms', 'kakao', 'email', 'whatsapp')),
  enabled    boolean NOT NULL DEFAULT false,
  config     jsonb   NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES users(id) ON DELETE SET NULL
);

INSERT INTO notify_channels (channel) VALUES
  ('telegram'), ('sms'), ('kakao'), ('email'), ('whatsapp')
ON CONFLICT (channel) DO NOTHING;

-- 수신자. 한 사람이 여러 경로로 받도록 여러 줄을 등록할 수 있습니다.
CREATE TABLE IF NOT EXISTS notify_recipients (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  channel    text NOT NULL
             CHECK (channel IN ('telegram', 'sms', 'kakao', 'email', 'whatsapp')),
  -- 전화번호 · 텔레그램 chat_id · 메일 주소
  target     text NOT NULL,
  -- 이 등급 이상일 때만 보냅니다.
  min_level  text NOT NULL DEFAULT 'warning'
             CHECK (min_level IN ('caution', 'warning', 'danger')),
  -- 야간 미발송 구간(시). 둘 다 NULL 이면 항상 발송합니다.
  -- 위험(danger) 등급은 이 구간에도 보냅니다.
  quiet_from smallint CHECK (quiet_from BETWEEN 0 AND 23),
  quiet_to   smallint CHECK (quiet_to   BETWEEN 0 AND 23),
  enabled    boolean NOT NULL DEFAULT true,
  memo       text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 같은 경로에 같은 번호를 두 번 등록해 중복 발송되는 일을 막습니다.
CREATE UNIQUE INDEX IF NOT EXISTS notify_recipients_uniq
  ON notify_recipients (channel, target);

-- 발송 이력. 성공·실패·건너뜀을 모두 남겨 추적할 수 있게 합니다.
CREATE TABLE IF NOT EXISTS notify_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alarm_id     bigint,
  recipient_id bigint,
  recipient    text,
  channel      text NOT NULL,
  target       text NOT NULL,
  level        text,
  body         text NOT NULL,
  status       text NOT NULL CHECK (status IN ('sent', 'failed', 'skipped')),
  error        text,
  provider_id  text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notify_log_created_idx ON notify_log (created_at DESC);
CREATE INDEX IF NOT EXISTS notify_log_alarm_idx   ON notify_log (alarm_id);

-- 같은 알람을 워커가 두 번 집어도 한 번만 보내도록, 처리 완료 표시를 둡니다.
CREATE TABLE IF NOT EXISTS notify_dispatched (
  alarm_id     bigint PRIMARY KEY,
  dispatched_at timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 8. 수집 연동 (브로커 설정 · 수신 내역 · 장비 명령)
--    반복 실행해도 안전합니다.
-- ----------------------------------------------------------------------------

-- 브로커 접속 정보. 수집기가 기동 시와 주기적으로 읽어 반영합니다.
-- 비밀번호가 들어가므로 화면으로는 설정 여부만 내려보냅니다.
CREATE TABLE IF NOT EXISTS mqtt_config (
  id            integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  host          text    NOT NULL DEFAULT '127.0.0.1',
  port          integer NOT NULL DEFAULT 1883,
  username      text,
  password      text,
  tls           boolean NOT NULL DEFAULT false,
  ca_path       text,
  client_id     text    NOT NULL DEFAULT 'dh-collector',
  topic_prefix  text    NOT NULL DEFAULT 'dh/v1',
  site          text    NOT NULL DEFAULT 'dh1',
  -- 수신 내역을 며칠 보관할지. 지난 것은 수집기가 스스로 지웁니다.
  keep_log_days integer NOT NULL DEFAULT 7,
  version       integer NOT NULL DEFAULT 1,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid REFERENCES users(id) ON DELETE SET NULL
);

INSERT INTO mqtt_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 수집기가 살아 있는지, 브로커에 붙어 있는지 화면에서 보기 위한 자리입니다.
CREATE TABLE IF NOT EXISTS collector_status (
  id              integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  connected       boolean NOT NULL DEFAULT false,
  broker          text,
  last_error      text,
  started_at      timestamptz,
  last_heartbeat  timestamptz,
  last_message_at timestamptz,
  messages        bigint NOT NULL DEFAULT 0,
  rows_stored     bigint NOT NULL DEFAULT 0,
  alarms          bigint NOT NULL DEFAULT 0,
  errors          bigint NOT NULL DEFAULT 0,
  config_version  integer
);

INSERT INTO collector_status (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 수신 내역. 장비가 실제로 무엇을 보냈는지 원문 그대로 남겨,
-- 규격이 맞지 않을 때 어느 쪽 문제인지 바로 확인할 수 있게 합니다.
CREATE TABLE IF NOT EXISTS ingest_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic        text NOT NULL,
  src_type     text,
  src_id       text,
  kind         text,
  device_ids   text[],
  item_count   integer NOT NULL DEFAULT 0,
  stored_count integer NOT NULL DEFAULT 0,
  replay       boolean NOT NULL DEFAULT false,
  status       text NOT NULL CHECK (status IN ('ok', 'warn', 'error')),
  message      text,
  payload      jsonb,
  received_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ingest_log_time_idx   ON ingest_log (received_at DESC);
CREATE INDEX IF NOT EXISTS ingest_log_status_idx ON ingest_log (status, received_at DESC);

-- 서버 → 장비 명령. 화면에서 넣으면 수집기가 집어 MQTT 로 내보냅니다.
CREATE TABLE IF NOT EXISTS device_commands (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site         text NOT NULL DEFAULT 'dh1',
  target_type  text NOT NULL CHECK (target_type IN ('bridge', 'module', 'gateway')),
  target_id    text NOT NULL,
  -- 특정 설비 하나를 지정할 때만 씁니다.
  device_id    text,
  command      text NOT NULL,
  params       jsonb NOT NULL DEFAULT '{}'::jsonb,
  status       text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending', 'sent', 'acked', 'failed', 'timeout')),
  requested_by uuid REFERENCES users(id) ON DELETE SET NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  sent_at      timestamptz,
  acked_at     timestamptz,
  ack          jsonb,
  error        text
);

CREATE INDEX IF NOT EXISTS device_commands_time_idx   ON device_commands (requested_at DESC);
CREATE INDEX IF NOT EXISTS device_commands_status_idx ON device_commands (status, requested_at);

-- 명령이 들어오면 수집기가 곧바로 내보내도록 통지합니다.
CREATE OR REPLACE FUNCTION notify_device_command() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('device_command', NEW.id::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS device_commands_notify ON device_commands;
CREATE TRIGGER device_commands_notify
  AFTER INSERT ON device_commands
  FOR EACH ROW EXECUTE FUNCTION notify_device_command();

-- 브로커 설정이 바뀌면 수집기가 다시 접속하도록 통지합니다.
CREATE OR REPLACE FUNCTION notify_mqtt_config() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('mqtt_config', NEW.version::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS mqtt_config_notify ON mqtt_config;
CREATE TRIGGER mqtt_config_notify
  AFTER UPDATE ON mqtt_config
  FOR EACH ROW EXECUTE FUNCTION notify_mqtt_config();

-- ----------------------------------------------------------------------------
-- 9. 장비 구성 3안 수용  (㈜헤디 2026-10 협의 반영)
--
--    1안  측정모듈 → (MQTT) → 서버
--    2안  측정모듈 → (RS-485) → 사용자 PC → (MQTT) → 서버
--    3안  측정모듈 → (RS-485) → 브릿지 → (MQTT) → 서버
--
--    세 경우 모두 "설비(측정모듈)" 는 devices 에, 그 앞단에서 값을 모아
--    보내는 주체(브릿지 · PC 게이트웨이)는 bridges 에 담습니다.
--    1안은 앞단이 없으므로 devices.bridge_id 가 NULL 로 남습니다.
--    이 절은 반복 실행해도 안전합니다.
-- ----------------------------------------------------------------------------

-- 값을 모아 보내는 주체의 종류. 2안의 사용자 PC 도 여기에 들어갑니다.
ALTER TABLE bridges ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'bridge';
ALTER TABLE bridges DROP CONSTRAINT IF EXISTS bridges_kind_check;
ALTER TABLE bridges ADD CONSTRAINT bridges_kind_check
  CHECK (kind IN ('bridge', 'gateway'));

-- RS-485 한 가닥에 붙일 수 있는 최대 대수. 헤디 회신 기준 32대입니다.
ALTER TABLE bridges ADD COLUMN IF NOT EXISTS max_devices integer NOT NULL DEFAULT 32;

-- 설비가 서버까지 어떤 길로 오는지. 화면에서 구성을 구분해 보여주기 위한 값입니다.
ALTER TABLE devices ADD COLUMN IF NOT EXISTS link_type text NOT NULL DEFAULT 'bridge';
ALTER TABLE devices DROP CONSTRAINT IF EXISTS devices_link_type_check;
ALTER TABLE devices ADD CONSTRAINT devices_link_type_check
  CHECK (link_type IN ('direct', 'bridge', 'gateway'));

-- 1안처럼 모듈이 직접 붙는 경우, 모듈 자신의 접속 상태를 여기에 적습니다.
ALTER TABLE devices ADD COLUMN IF NOT EXISTS online       boolean NOT NULL DEFAULT false;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS fw_version   text;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS rssi         integer;
-- 장치에 설정된 측정 주기(초). 측정 주기 변경 명령이 성공하면 갱신됩니다.
ALTER TABLE devices ADD COLUMN IF NOT EXISTS interval_sec integer;

-- 앞단별 등록 대수를 세기 위한 색인입니다.
CREATE INDEX IF NOT EXISTS devices_bridge_idx ON devices (bridge_id);

-- 명령 응답 대기시간. 헤디 회신은 1초 이내이지만, 네트워크 왕복과
-- 브로커 지연을 감안해 기본 10초로 두고 화면에서 조정합니다.
ALTER TABLE mqtt_config ADD COLUMN IF NOT EXISTS ack_timeout_sec integer NOT NULL DEFAULT 10;

-- 재전송(미전송분 백필) 한 메시지에 담을 수 있는 최대 항목 수.
-- 브릿지가 최대 1개월분을 보관하므로, 한 번에 쏟아지지 않도록 상한을 둡니다.
ALTER TABLE mqtt_config ADD COLUMN IF NOT EXISTS max_replay_items integer NOT NULL DEFAULT 500;

-- 수신 내역의 원문 보관 상한. 재전송 메시지는 원문이 매우 크므로
-- 이 수를 넘는 항목은 요약만 남깁니다.
ALTER TABLE mqtt_config ADD COLUMN IF NOT EXISTS log_payload_items integer NOT NULL DEFAULT 20;

-- 유면 저하를 몇 등급으로 볼지. 웹 화면과 수집 서버가 같은 값을 씁니다.
-- (유면 규격은 헤디와 협의 중이며, 아날로그로 확정되면 임계치로 바뀝니다.)
UPDATE app_config
   SET thresholds = thresholds || '{"oilLowLevel": "warning"}'::jsonb
 WHERE id = 1 AND NOT (thresholds ? 'oilLowLevel');

-- 기존 데이터 정리: 앞단이 없는 설비는 직결로 표시합니다.
UPDATE devices SET link_type = 'direct' WHERE bridge_id IS NULL AND link_type = 'bridge';

-- 설비 목록이 바뀌면 수집기가 곧바로 다시 읽도록 통지합니다.
-- (화면에서 설비를 지운 직후 그 설비의 값이 들어오면, 수집기가 아직
--  예전 목록을 들고 있어 적재에 실패하는 일을 막습니다.)
CREATE OR REPLACE FUNCTION notify_devices_changed() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('devices_changed', COALESCE(NEW.device_id, OLD.device_id));
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS devices_changed_notify ON devices;
CREATE TRIGGER devices_changed_notify
  AFTER INSERT OR DELETE ON devices
  FOR EACH ROW EXECUTE FUNCTION notify_devices_changed();
